phrase:
  access_token: "b7fc60cd08e349735c546d147186900a91ec509bf763e515ea531affb3cd4c29"
  
  project_id: "80761a980dd2fcfb6b94827c5c46347e"

  file_format: "xml"

  push:

    sources:

    - file: "./Sample_<locale_code>.xml"
      params:
        locale_id: c8f305b04d1ec15bdddc36b0f7d13765

  pull:

    targets:

    - file: "./Sample_<locale_code>.xml"
      params:
        locale_id: a9e9caa3f256b37614ab465b49b451eb
